Import("env")
import os

def generate_fan_curve_header(source, target, env):
    # Path to CSV file
    csv_path = os.path.join(env.subst("$PROJECT_DIR"), "data", "fan_curve.csv")
    # Path to output header file
    header_path = os.path.join(env.subst("$PROJECT_DIR"), "include", "fan_curve_data.h")
    
    if not os.path.exists(csv_path):
        print(f"Warning: {csv_path} not found")
        return
    
    # Read CSV file and convert to C string
    with open(csv_path, 'r') as f:
        lines = f.readlines()
    
    # Filter out comments and empty lines, build CSV string
    csv_data = []
    for line in lines:
        line = line.strip()
        if line and not line.startswith('#'):
            csv_data.append(line)
    
    # Generate header file content
    header_content = f"""// Auto-generated from data/fan_curve.csv
// Do not edit this file manually

#ifndef FAN_CURVE_DATA_H
#define FAN_CURVE_DATA_H

#include <Arduino.h>

const char csvData[] PROGMEM = 
"""
    
    # Add each CSV line as a string
    for line in csv_data:
        header_content += f'"{line}\\n"\n'
    
    header_content += """;

#endif // FAN_CURVE_DATA_H
"""
    
    # Write header file
    with open(header_path, 'w') as f:
        f.write(header_content)
    
    print(f"Generated {header_path} from {csv_path}")

# Register the pre-build script
env.AddPreAction("$BUILD_DIR/${PROGNAME}.elf", generate_fan_curve_header)
