// Auto-generated from data/fan_curve.csv
// DO NOT EDIT THIS FILE DIRECTLY - Edit fan_curve.csv instead

#ifndef FAN_CURVE_DATA_H
#define FAN_CURVE_DATA_H

#include <Arduino.h>

// CSV data embedded in program memory (from fan_curve.csv)
const char csvData[] PROGMEM = 
"30,0.00\n"
"40,0.20\n"
"50,0.35\n"
"60,0.50\n"
"70,0.70\n"
"80,0.85\n"
"90,1.00\n"
;

#endif // FAN_CURVE_DATA_H
